apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-api
  labels:
    app: store-api
spec:
  selector:
    matchLabels:
      app: store-api
  template:
    metadata:
      labels:
        app: store-api
    spec:
      containers:
        - name: store-api
          image: store-api:v1
          ports:
            - containerPort: 8888
