// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"github.com/yakushou730/gozero-practice/product/rpc/internal/logic"
	"github.com/yakushou730/gozero-practice/product/rpc/internal/svc"
	"github.com/yakushou730/gozero-practice/product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) ProductList(ctx context.Context, in *product.ProductListRequest) (*product.ProductListResponse, error) {
	l := logic.NewProductListLogic(ctx, s.svcCtx)
	return l.ProductList(in)
}
