// Code generated by goctl. DO NOT EDIT.
package types

type ProductListRequest struct {
}

type ProductResponse struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type ProductListResponse struct {
	Products []ProductResponse `json:"products"`
}
