// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/yakushou730/gozero-practice/store/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: GetProductsHandler(serverCtx),
			},
		},
	)
}
